services:
  db:
    image: postgres:16
    container_name: avuea-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_chat
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile   # usa o Dockerfile da raiz
    container_name: avuea-backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/rag_chat
      - PDF_DIR=/app/data/pdfs
      - VECTORSTORE_DIR=/app/data/vectorstore
    volumes:
      - ./backend/data:/app/data   # opcional, mas bom pra persistir o vectorstore
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
